remote_theme: pages-themes/hacker@v0.2.0 # this line adds the slate theme of Jekyll. You can replace "slate@v0.2.0" with your preferred theme.

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "CV DE CLEMENT FALCON" # Replace "[Your Name]" with your first and last name.
show_downloads: false
description: "Le CV de Clément Falcon, étudiant à l'INSA Hauts-de-France"
